import * as frm from "form-group";
import * as tif from "text-input-floating";
import * as taif from "text-area-input-floating";
import * as tidp from "text-input-date-picker";
import * as add from "address";
import * as ph from "phone";
import * as cnm from "confirm-navigation-modal";
import * as pm from "progress-meter";
import * as cf from "custom-fields";
import * as pl from "item-pick-list";
import * as chk from "checkbox-input";

export const {FormGroup} = frm;
export const {TextInputFloating} = tif;
export const {TextAreaInputFloating} = taif;
export const {TextInputDatePicker} = tidp;
export const Address = add.AddressMain;
export const Checkbox = chk.CheckboxInput;
export const Phone = ph.PhoneMain;
export const {ConfirmNavigationModal} = cnm;
export const PieChart = pm.ProgressMeterMain;
export const CustomFields = cf.CustomFields;
export const ItemPickList = pl.ItemPickList;
